[package]
publish = false
name = "turna-observability"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
thiserror.workspace = true
hostname.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry.workspace = true
tracing-subscriber.workspace = true
