[package]
publish = false
name    = "turna-management"
version.workspace = true
edition.workspace = true

[dependencies]
tokio       = { workspace = true, features = ["net", "io-util"] }
serde       = { workspace = true, features = ["derive"] }
serde_json.workspace  = true
tracing.workspace     = true
async-trait           = "0.1"
turna-health.workspace  = true
