{{- if and .Values.turn.auth.sharedSecret (not .Values.turn.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-turn-auth
  labels:
    app.kubernetes.io/name: turna
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  shared-secret: {{ .Values.turn.auth.sharedSecret | quote }}
{{- end }}
